spring:
  main:
    web-application-type: servlet

server:
  url: http://localhost:8081
  port: 8081
  address: 0.0.0.0

ai:
  ollama:
    baseURL: http://localhost:11434
    chat:
      options:
        model: gemma2
        temperature: 0.7