spring:
  main:
    web-application-type: servlet

server:
  address: 0.0.0.0
  port: 8081

ai:
  ollama:
    baseURL: http://localhost:11434
    chat:
      options:
        model: gemma2
        temperature: 0.7